#############################################################################
# Makefile for building: StockTraderClient
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  StockTraderClient.pro
# Template: app
# Command: E:/anaconda/Library/bin/qmake.exe -o Makefile StockTraderClient.pro -spec win32-g++
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = E:/anaconda/Library/bin/qmake.exe
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = cp -f
INSTALL_PROGRAM = cp -f
INSTALL_DIR   = cp -f -R
QINSTALL      = E:/anaconda/Library/bin/qmake.exe -install qinstall
QINSTALL_PROGRAM = E:/anaconda/Library/bin/qmake.exe -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
IDC           = idc
IDL           = midl
ZIP           = 
DEF_FILE      = 
RES_FILE      = 
SED           = sed
MOVE          = mv -f
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: StockTraderClient.pro ../../../anaconda/Library/mkspecs/win32-g++/qmake.conf ../../../anaconda/Library/mkspecs/features/spec_pre.prf \
		../../../anaconda/Library/mkspecs/qdevice.pri \
		../../../anaconda/Library/mkspecs/features/device_config.prf \
		../../../anaconda/Library/mkspecs/common/sanitize.conf \
		../../../anaconda/Library/mkspecs/common/gcc-base.conf \
		../../../anaconda/Library/mkspecs/common/g++-base.conf \
		../../../anaconda/Library/mkspecs/common/angle.conf \
		../../../anaconda/Library/mkspecs/features/win32/windows_vulkan_sdk.prf \
		../../../anaconda/Library/mkspecs/common/windows-vulkan.conf \
		../../../anaconda/Library/mkspecs/common/g++-win32.conf \
		../../../anaconda/Library/mkspecs/common/windows-desktop.conf \
		../../../anaconda/Library/mkspecs/qconfig.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_3danimation.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_3dcore.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_3dextras.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_3dinput.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_3dquick.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_3drender.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_axbase.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_axbase_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_axcontainer.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_axcontainer_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_axserver.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_axserver_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_charts.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_charts_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_concurrent.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_core.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_core_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_dbus.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_designer.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_designer_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_gamepad.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_gui.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_gui_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_help.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_help_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_location.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_location_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_multimedia.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_network.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_network_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_networkauth.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_nfc.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_opengl.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_pdf.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_pdf_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_pdfwidgets.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_positioning.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_printsupport.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_purchasing.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_qml.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_qml_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_qmltest.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_quick.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_quick3d.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_quick3drender.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_quick3drender_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_quick_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_repparser.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_script.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_script_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_scripttools.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_scxml.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_sensors.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_serialbus.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_serialport.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_sql.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_sql_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_svg.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_svg_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_testlib.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_uitools.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_webchannel.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_webengine.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_websockets.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_webview.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_webview_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_widgets.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_winextras.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_winextras_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_xml.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_xml_private.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../anaconda/Library/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../anaconda/Library/mkspecs/features/qt_functions.prf \
		../../../anaconda/Library/mkspecs/features/qt_config.prf \
		../../../anaconda/Library/mkspecs/win32-g++/qmake.conf \
		../../../anaconda/Library/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../anaconda/Library/mkspecs/features/exclusive_builds.prf \
		../../../anaconda/Library/mkspecs/features/toolchain.prf \
		../../../anaconda/Library/mkspecs/features/default_pre.prf \
		../../../anaconda/Library/mkspecs/features/win32/default_pre.prf \
		../../../anaconda/Library/mkspecs/features/resolve_config.prf \
		../../../anaconda/Library/mkspecs/features/exclusive_builds_post.prf \
		../../../anaconda/Library/mkspecs/features/default_post.prf \
		../../../anaconda/Library/mkspecs/features/precompile_header.prf \
		../../../anaconda/Library/mkspecs/features/warn_on.prf \
		../../../anaconda/Library/mkspecs/features/qt.prf \
		../../../anaconda/Library/mkspecs/features/resources_functions.prf \
		../../../anaconda/Library/mkspecs/features/resources.prf \
		../../../anaconda/Library/mkspecs/features/moc.prf \
		../../../anaconda/Library/mkspecs/features/win32/opengl.prf \
		../../../anaconda/Library/mkspecs/features/uic.prf \
		../../../anaconda/Library/mkspecs/features/qmake_use.prf \
		../../../anaconda/Library/mkspecs/features/file_copies.prf \
		../../../anaconda/Library/mkspecs/features/win32/windows.prf \
		../../../anaconda/Library/mkspecs/features/testcase_targets.prf \
		../../../anaconda/Library/mkspecs/features/exceptions.prf \
		../../../anaconda/Library/mkspecs/features/yacc.prf \
		../../../anaconda/Library/mkspecs/features/lex.prf \
		StockTraderClient.pro \
		../../../anaconda/Library/mkspecs/features/build_pass.prf \
		resources.qrc
	$(QMAKE) -o Makefile StockTraderClient.pro -spec win32-g++
../../../anaconda/Library/mkspecs/features/spec_pre.prf:
../../../anaconda/Library/mkspecs/qdevice.pri:
../../../anaconda/Library/mkspecs/features/device_config.prf:
../../../anaconda/Library/mkspecs/common/sanitize.conf:
../../../anaconda/Library/mkspecs/common/gcc-base.conf:
../../../anaconda/Library/mkspecs/common/g++-base.conf:
../../../anaconda/Library/mkspecs/common/angle.conf:
../../../anaconda/Library/mkspecs/features/win32/windows_vulkan_sdk.prf:
../../../anaconda/Library/mkspecs/common/windows-vulkan.conf:
../../../anaconda/Library/mkspecs/common/g++-win32.conf:
../../../anaconda/Library/mkspecs/common/windows-desktop.conf:
../../../anaconda/Library/mkspecs/qconfig.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_3danimation.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_3dcore.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_3dextras.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_3dinput.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_3dlogic.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_3dquick.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_3drender.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_3drender_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_axbase.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_axbase_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_axcontainer.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_axcontainer_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_axserver.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_axserver_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_bluetooth.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_bodymovin_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_charts.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_charts_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_concurrent.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_core.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_core_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_datavisualization.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_dbus.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_dbus_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_designer.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_designer_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_edid_support_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_egl_support_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_gamepad.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_gui.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_gui_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_help.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_help_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_location.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_location_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_multimedia.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_network.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_network_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_networkauth.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_nfc.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_nfc_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_opengl.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_opengl_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_openglextensions.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_pdf.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_pdf_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_pdfwidgets.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_positioning.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_positioning_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_positioningquick.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_printsupport.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_purchasing.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_qml.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_qml_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_qmlmodels.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_qmltest.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_quick.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_quick3d.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_quick3d_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_quick3dassetimport.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_quick3drender.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_quick3drender_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_quick3druntimerender.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_quick3dutils.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_quick3dutils_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_quick_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_remoteobjects.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_repparser.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_repparser_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_script.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_script_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_scripttools.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_scxml.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_scxml_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_sensors.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_sensors_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_serialbus.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_serialport.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_serialport_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_sql.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_sql_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_svg.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_svg_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_testlib.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_testlib_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_texttospeech.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_uiplugin.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_uitools.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_uitools_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_webchannel.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_webengine.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_webengine_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_webenginecore.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_websockets.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_websockets_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_webview.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_webview_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_widgets.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_widgets_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_winextras.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_winextras_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_xml.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_xml_private.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../anaconda/Library/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../anaconda/Library/mkspecs/features/qt_functions.prf:
../../../anaconda/Library/mkspecs/features/qt_config.prf:
../../../anaconda/Library/mkspecs/win32-g++/qmake.conf:
../../../anaconda/Library/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../anaconda/Library/mkspecs/features/exclusive_builds.prf:
../../../anaconda/Library/mkspecs/features/toolchain.prf:
../../../anaconda/Library/mkspecs/features/default_pre.prf:
../../../anaconda/Library/mkspecs/features/win32/default_pre.prf:
../../../anaconda/Library/mkspecs/features/resolve_config.prf:
../../../anaconda/Library/mkspecs/features/exclusive_builds_post.prf:
../../../anaconda/Library/mkspecs/features/default_post.prf:
../../../anaconda/Library/mkspecs/features/precompile_header.prf:
../../../anaconda/Library/mkspecs/features/warn_on.prf:
../../../anaconda/Library/mkspecs/features/qt.prf:
../../../anaconda/Library/mkspecs/features/resources_functions.prf:
../../../anaconda/Library/mkspecs/features/resources.prf:
../../../anaconda/Library/mkspecs/features/moc.prf:
../../../anaconda/Library/mkspecs/features/win32/opengl.prf:
../../../anaconda/Library/mkspecs/features/uic.prf:
../../../anaconda/Library/mkspecs/features/qmake_use.prf:
../../../anaconda/Library/mkspecs/features/file_copies.prf:
../../../anaconda/Library/mkspecs/features/win32/windows.prf:
../../../anaconda/Library/mkspecs/features/testcase_targets.prf:
../../../anaconda/Library/mkspecs/features/exceptions.prf:
../../../anaconda/Library/mkspecs/features/yacc.prf:
../../../anaconda/Library/mkspecs/features/lex.prf:
StockTraderClient.pro:
../../../anaconda/Library/mkspecs/features/build_pass.prf:
resources.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile StockTraderClient.pro -spec win32-g++

qmake_all: FORCE

make_first: release-make_first debug-make_first  FORCE
all: release-all debug-all  FORCE
clean: release-clean debug-clean  FORCE
distclean: release-distclean debug-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash

release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first

benchmark: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
